"""Make currency private to user

Revision ID: 1eb371e1aeee
Revises: a18826c91512
Create Date: 2026-06-22 17:13:07.221457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb371e1aeee'
down_revision: Union[str, Sequence[str], None] = 'a18826c91512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currencies', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'currencies', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currencies', type_='foreignkey')
    op.drop_column('currencies', 'user_id')
    # ### end Alembic commands ###
